RentalIncomeCalculator/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name = 'users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name = 'users/logout.html'), name='logout'),
    path('', include('calculator.urls')),
]

calculator/urls.py
from django.urls import path
from . import views
from .views import TransactionView
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.conf.urls.static import static 



urlpatterns = [
    path('', views.TransactionAllView, name='calculator-transactions'),
    path('transactions/<int:pk>/', views.TransactionView.as_view(), name='calculator-transaction'),
    path('transactions/create-transaction/<int:pk>/', views.TransactionCreate.as_view(), name='transaction-create'),
    path('transactions/create-ru/', views.RentalUnitCreate.as_view(), name='rentalunit-create'),
    path('transactions/delete-transaction/<int:pk>/', views.TransactionDelete.as_view(), name='transaction-delete'),
    path('transactions/delete-ru/<int:pk>/', views.RentalUnitDelete.as_view(), name='rentalunit-delete'),

    path('report/<int:year>/', views.Report, name='calculator-report'),
    path('report/<int:year>/<int:pk>/', views.ReportSingleRU, name='calculator-report'),
    ]

if settings.DEBUG:

    #urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

calculator/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from partial_date import PartialDateField
from django.urls import reverse

class RentalUnit(models.Model):
	owner = models.ForeignKey(User, on_delete = models.CASCADE)

	RENTAL_TYPES = (
	    ('A','Apartment'),
	    ('G','Garage'),
	    ('H','House'),
	)

	rental_unit_type = models.CharField(max_length=1, choices=RENTAL_TYPES)
	address_city = models.CharField(max_length = 50)
	address_street = models.CharField(max_length = 50)
	address_zip_code = models.CharField(max_length = 10)
	address_number = models.CharField(max_length = 10)

	class Meta:
		ordering = ['address_city','address_street','address_number']
	
	def get_address(self):
		return " ".join([self.address_city, self.address_street, self.address_number])


	def __str__(self):
		return " ".join([self.rental_unit_type+".", self.address_city, self.address_street, self.address_number])

	def get_absolute_url(self):
		return reverse('calculator-transactions')

class Transaction(models.Model):
	rental_unit_id = models.ForeignKey(RentalUnit, on_delete = models.CASCADE)

	TRANSACTION_TYPES = (
		('R','Revenue'),
		('I','Insurance'),
		('P','Property Taxes'),
		('E','Electricity'),
		('A','Administration fees'),
		('O','Other'),
	)

	transaction_type = models.CharField(max_length=1, choices=TRANSACTION_TYPES)
	transaction_date = models.DateField()
	amount = models.DecimalField(max_digits=10, decimal_places = 2)
	comments = models.CharField(max_length = 1000, null=True)

	
	pdf_file = models.FileField(upload_to="media/",blank=True, null=True)

	def __str__(self):
		return " ".join([str(self.rental_unit_id), self.transaction_type, str(self.transaction_date), str(self.amount)]) 

	def get_absolute_url(self):
		return reverse('calculator-transactions')

calculator/views.py
from django.shortcuts import render
from .models import Transaction, RentalUnit
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic import TemplateView, CreateView, DeleteView
from .filters import TransactionFilter
from django.urls import reverse_lazy
from django.core.files.storage import FileSystemStorage


@login_required
def TransactionAllView(request):
	context = {}
	context['rental_units'] = RentalUnit.objects.filter(owner = request.user)
	
	def recursiveTransactionQuerySet(rentals, transaction_set):
		return transaction_set.filter(rental_unit_id__in = context['rental_units'])
		
	context['transactions'] = recursiveTransactionQuerySet(context['rental_units'],Transaction.objects.all().order_by('-transaction_date'))

	myFilter = TransactionFilter(request.GET, queryset=context['transactions'])
	context['myFilter'] = myFilter
	context['transactions'] = myFilter.qs

	
	context['months'] = ['January','Febrary','March','April','May','June','July','August','September','October','November','December']


	return render(request,'calculator/transactions.html',context)

class TransactionView(DetailView):
	model =  RentalUnit
	def get_context_data(self, **kwargs):
		context = {}

		context['rental'] = self.get_object()
		context['rental_units'] = RentalUnit.objects.filter(owner = self.request.user)
			
		context['transactions'] = Transaction.objects.filter(rental_unit_id = context['rental']).order_by('-transaction_date')

		myFilter = TransactionFilter(self.request.GET, queryset=context['transactions'])
		context['myFilter'] = myFilter
		context['transactions'] = myFilter.qs

		context['months'] = ['January','Febrary','March','April','May','June','July','August','September','October','November','December']
		return context

class TransactionCreate(LoginRequiredMixin, CreateView):
    model = Transaction
    fields = ['transaction_type', 'transaction_date', 'amount', 'comments','pdf_file']

    def form_valid(self, form):
    	form.instance.rental_unit_id = RentalUnit.objects.get(pk=self.kwargs.get('pk'))
    	return super().form_valid(form)

    def get_context_data(self, **kwargs):
    	context = super(TransactionCreate, self).get_context_data(**kwargs)
    	context['rental_units'] = RentalUnit.objects.filter(owner = self.request.user)
    	return context

class TransactionDelete(LoginRequiredMixin, DeleteView):
	model = Transaction
	success_url = reverse_lazy('calculator-transactions')

class RentalUnitCreate(LoginRequiredMixin, CreateView):
    model = RentalUnit
    fields = ['rental_unit_type', 'address_city', 'address_street', 'address_zip_code', 'address_number']

    def form_valid(self, form):
    	form.instance.owner = self.request.user
    	return super().form_valid(form)

    def get_context_data(self, **kwargs):
    	context = super(RentalUnitCreate, self).get_context_data(**kwargs)
    	context['rental_units'] = RentalUnit.objects.filter(owner = self.request.user)
    	return context

class RentalUnitDelete(LoginRequiredMixin, DeleteView):
    model = RentalUnit
    success_url = reverse_lazy('calculator-transactions')

    def test_func(self):
    	ru = self.get_object()
    	if self.user.request == ru.owner:
    		return True
    	return False


@login_required
def DisplayPDF(request, url):
	image_data = open(url, "rb").read()
	return HttpResponse(image_data, mimetype="application/pdf")


# ------------------------------------------- #

@login_required
def Report(request, year):
	context = {'title': "Report"}
	context['rental_units'] = RentalUnit.objects.filter(owner = request.user)
	context["rental_units_count"] = RentalUnit.objects.filter(owner = request.user).count()
	context["this_year"] = year

	def recursiveTransactionQuerySet(rentals, transaction_set):
		return transaction_set.filter(rental_unit_id__in = context['rental_units'])

	transactions = recursiveTransactionQuerySet(context['rental_units'],Transaction.objects.all())
	context["transactions_count"] = transactions.count()
	context["months"] = ["January","February","March","April","May","June","July","August","September","October","November","December"]

	def createlist():
		l = []
		for row in range(12):
			l.append([0.00,0.00,0.00])
		return l

	transactions_years = {year:createlist()}
	transactions_years_total = {year:[0.0,0.0,0.0]}
	years = set()
	total_profit = 0.0
		
	for transaction in transactions:		
		year = transaction.transaction_date.year
		years.add(year)
		month = transaction.transaction_date.month - 1
		if year not in transactions_years.keys():
			transactions_years[year] = createlist()  # total/months, rev/exp/tot
			transactions_years_total[year] = [0.0,0.0,0.0]
		amount = transaction.amount
		trans_type = transaction.transaction_type
		if trans_type == 'R':
			transactions_years[year][month][0] += float(amount)
			transactions_years[year][month][2] += float(amount)
			transactions_years_total[year][0] += float(amount)
			transactions_years_total[year][2] += float(amount)
			total_profit += float(amount)
		else:
			transactions_years[year][month][1] -= float(amount)
			transactions_years[year][month][2] -= float(amount)
			transactions_years_total[year][1] -= float(amount)
			transactions_years_total[year][2] -= float(amount)
			total_profit -= float(amount)

	context['total_profit'] = total_profit
	context['transactions_years_total'] = transactions_years_total
	context['transactions_years'] = transactions_years
	context['years'] = sorted(list(years))[::-1]

	return render(request, 'calculator/report.html', context)

@login_required
def ReportSingleRU(request, year, pk):
	context = {'title': "Report"}
	context['rental_units'] = RentalUnit.objects.filter(owner = request.user)
	context["rental_units_count"] = RentalUnit.objects.filter(owner = request.user).count()
	context['rental'] = RentalUnit.objects.get(pk=pk)
	context["this_year"] = year


	def recursiveTransactionQuerySet(rentals, transaction_set):
		return transaction_set.filter(rental_unit_id__in = context['rental_units'])

	total_transactions_count = recursiveTransactionQuerySet(context['rental_units'],Transaction.objects.all()).count()
	context["transactions_count"] = total_transactions_count

	transactions = Transaction.objects.filter(rental_unit_id = context['rental']).order_by('-transaction_date')
	context["this_transactions_count"] = transactions.count()
	context["months"] = ["January","February","March","April","May","June","July","August","September","October","November","December",]

	def createlist():
		l = []
		for row in range(12):
			l.append([0.0,0.0,0.0])
		return l

	transactions_years = {year:createlist()}
	transactions_years_total = {year:[0.0,0.0,0.0]}
	years = set()
	this_total_profit = 0.0
		
	for transaction in transactions:		
		year = transaction.transaction_date.year
		years.add(year)
		month = transaction.transaction_date.month - 1
		if year not in transactions_years.keys():
			transactions_years[year] = createlist()  # total/months, rev/exp/tot
			transactions_years_total[year] = [0.0,0.0,0.0]
		amount = transaction.amount
		trans_type = transaction.transaction_type
		if trans_type == 'R':
			transactions_years[year][month][0] += float(amount)
			transactions_years[year][month][2] += float(amount)
			transactions_years_total[year][0] += float(amount)
			transactions_years_total[year][2] += float(amount)
			this_total_profit += float(amount)
		else:
			transactions_years[year][month][1] -= float(amount)
			transactions_years[year][month][2] -= float(amount)
			transactions_years_total[year][1] -= float(amount)
			transactions_years_total[year][2] -= float(amount)
			this_total_profit -= float(amount)

	context['this_total_profit'] = this_total_profit
	context['transactions_years_total'] = transactions_years_total
	context['transactions_years'] = transactions_years
	context['years'] = sorted(list(years))[::-1]

	return render(request, 'calculator/report.html', context)

calculator/templates/calculator/rentalunit_confirm_delete.html
{% extends "calculator/base.html" %}

{% block content %}
<form method="post">
	{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>
{% endblock content %}

calculator/templates/calculator/rentalunit_detail.html
{% extends 'calculator/base.html' %}

{% load widget_tweaks %}

{% block content %}

{% for trans in transactions%}
	<!-- Modal -->
	<div class="modal fade" id="MyModal{{trans.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	  <div class="modal-dialog">
	    <div class="modal-content">
	      <div class="modal-header">
	        <h5 class="modal-title" id="exampleModalLabel">Comment</h5>
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
	          <span aria-hidden="true">&times;</span>
	        </button>
	      </div>
	      <div class="modal-body">
	      	<h6 class="pb-2">for:  {{trans}}</h6>
	      	<h6>comment:  <strong>{{trans.comments}}</strong></h6>
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
	      </div>
	    </div>
	  </div>
	</div>
{% endfor %}


<h2 class="text-center font-weight-bolder py-2"> Transactions: {{rental}} </h2>


<div class="row justify-content-md pt-2">
	<div class = "col col-9">
		<a type="button" class="btn btn-outline-info btn-block" href="{% url 'transaction-create' rental.pk %}">Add a Transaction for this Rental Unit</a>`
	</div>
	<div class = "col col-3">
		<a type="button" class="btn btn-outline-dark btn-block" href="{% url 'rentalunit-delete' rental.pk %}">Delete this Rental Unit</a>`
	</div>
</div>

<div class="py-2">
		<form method="get">
			<div class="row">
				<div class = "col col-5">
					<div class="input-group mb-1">
					  <div class="input-group-prepend">
					    <span class="input-group-text" id="basic-addon1">
					    	Select date from:
					    </span>
					  </div>
					  {% render_field myFilter.form.date_from class="form-control" placeholder="YYYY-MM-DD"%}
					</div>
				</div>

				<div class = "col col-5">
					<div class="input-group mb-1">
					  <div class="input-group-prepend">
					    <span class="input-group-text" id="basic-addon1">
					    	Select date to:
					    </span>
					  </div>
					  {% render_field myFilter.form.date_to class="form-control" placeholder="YYYY-MM-DD"%}
					</div>
				</div>

				<div class = "col col-1">
					<button class="btn btn-primary" type="submit">Search</button>
				</div>
			</div>

		</form>
</div>


	<!-- table-->
	<table class="table table-hover">
	  <thead>
	    <tr>
	      <th scope="col" class= text>#</th>
	      <th scope="col" class= text>Rental Unit</th>
	      <th scope="col" class= text>Transaction type</th>
	      <th scope="col" class= text-center>Amount</th>
	      <th scope="col" class= text-center>Date</th>
	      <th scope="col" class= text-center>Comments</th>
	      <th scope="col" class= text-center>PDF</th>
	      <th scope="col" class= text>Remove</th>
	    </tr>
	  </thead>
	  
	  <tbody>
	  {% for trans in transactions%}
	    <tr>

	  		<th scope="row">{{ forloop.counter}}</th>
	  		<td class="text">{{trans.rental_unit_id}}</th>

	    	{% if trans.transaction_type == "R"%}
	      		<td class="text-success text">{{trans.get_transaction_type_display}}</td>
	      		<td class="text-success text-center">{{trans.amount}}</td>
	      	{% else %}
	      		<td class="text-danger text">{{trans.get_transaction_type_display}}</td>
	      		<td class="text-danger text-center">{{trans.amount}}</td>
	      	{% endif %}

	      	<td class="text-center">{{trans.transaction_date}}</td>

	    	<!-- Comment button trigger modal -->
			{% if trans.comments != "-"%}
				<td class="text-center">
					<button type="button" class="btn btn-outline-dark" data-toggle="modal" data-target="#MyModal{{trans.id}}">View
					</button>
				</td>
			{% else %}
				<td class="text-center">-</td>
			{% endif %}

	      	{% if trans.pdf_file %}
	      		<td><a class="link" href="% url {{trans.pdf_file.url}}%">view</a></td>
	      	{% else %}
	      		<td class="text-center">No File</td>
	      	{% endif %}

	      	<td>
	      		<a class="btn btn-secondary" href="{% url 'transaction-delete' trans.pk %}">delete</a>
	      	</td>
	    </tr>	    
	  {% endfor %}
	  </tbody>

	</table>


{% endblock content %}

calculator/templates/calculator/report.html
{% extends 'calculator/base.html' %}

{% load calculator_extras %}

{% block content %}

<div class="pb-3 text-center">
	<h4>
	Report for
	<strong>{% if rental%}{{rental}}{%else%}all rental units{%endif%}</strong>
	in
	<strong>{{this_year}}</strong>
	:
	</h4>
</div>


<div class='row'>
	<div class="col offset-1 col-6">
		<div class="mb-2">
			<div class='row'>
				<!-- select year dropdown-->
				<div class="col col-4">
					<div class="dropdown">
					  <a class="btn btn-outline-primary btn-sm dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					    Select rental unit
					  </a>
					  <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
					  	<a class="dropdown-item" href="{% url 'calculator-report' this_year %}">All</a>
					  	{%for ru in rental_units%}
					    <a class="dropdown-item" href="{% url 'calculator-report' this_year ru.pk %}">{{ru}}</a>
					    {% endfor %}
					  </div>
					</div>
				</div>
				<!-- select year dropdown-->
				<div class="col offset-5 col-3">
					<div class="dropdown">
					  <a class="btn btn-outline-primary btn-sm dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					    Select year
					  </a>
					  <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
					  	{%for year in years%}
					    <a class="dropdown-item" href="{% url 'calculator-report' year %}">{{year}}</a>
					    {% endfor %}
					  </div>
					</div>
				</div>
				
			</div>
		</div>


		<!-- table-->
		<table class="table table-hover  table-sm">
		  <thead>
		    <tr>
		      <th scope="col" class= "text">Month</th>
		      <th scope="col" class= "text text-right">Revenues</th>
		      <th scope="col" class= "text text-right">Expenses</th>
		      <th scope="col" class= "text text-right">Total</th>
		    </tr>
		  </thead>
		  
		  <tbody>
		  {% for row in transactions_years|get_value:this_year %}  
		    <tr>
	    		<td class="text">{{months|get_value_by_index:forloop.counter0}}</td>
	    		{% if row.0 > 0 %}
		    		<td class="text text-success text-right">{{row.0|floatformat:2}}</td>
	    		{% else %}
	    			<td class="text text-right">{{row.0|floatformat:2}}</td>
    			{% endif %}

	    		{% if row.1 < 0 %}
	    			<td class="text text-danger text-right">{{row.1|floatformat:2}}</td>
	    		{% else %}
	    			<td class="text text-right">{{row.1|floatformat:2}}</td>
	    		{% endif %}

	    		{% if row.2 > 0 %}
		    		<td class="text text-success text-right">{{row.2|floatformat:2}}</td>
	    		{% elif row.2 < 0  %}
	    			<td class="text text-danger text-right">{{row.2|floatformat:2}}</td>
	    		{% else %}
	    			<td class="text text-right">{{row.2|floatformat:2}}</td>
	    		{% endif %}
		    </tr>	    
		  {% endfor %}
		  	<tr>
		  		<td class="text"><h6><strong>Total:</strong></h6></td>
	    	{% for value in transactions_years_total|get_value:this_year %}
	    		{% if value > 0 %}
	    		<td class="text text-right"><h6 ><strong class="text-success">{{value|floatformat:2}}</strong></h6></td>
	    		{% elif value < 0 %}
	    		<td class="text text-right"><h6 ><strong class="text-danger">{{value|floatformat:2}}</strong></h6></td>
	    		{% else %}
	    		<td class="text text-right"><h6><strong>{{value|floatformat:2}}</strong></h6></td>
	    		{% endif %}
	    	{% endfor %}
	    	</tr>	


		  </tbody>
		</table>
	</div>
	<div class="col col-5 my-2">
		<div class="mx-auto" style="width: 200px;">
			{% if rental %}
				<div class="pb-3">
					<div class="card" style="width: 16rem">
					  <div class="card-body mb-1">   
					  	<h6 class="card-title my-2 text-center text-dark">
					    	Info about this rental unit:
					    </h6>
					    <h6 class="card-title my-2 text-center text-dark">
					    	Type: {{rental.get_rental_unit_type_display}}
					    </h6>
					    <h6 class="card-title my-2 text-center text-dark">
					    	ZIP: {{rental.address_zip_code}}
					    </h6>
					    <h6 class="card-title my-1 text-center text-dark">
					    	Address: 
					    </h6>
					    <h6 class="card-title my-1 text-center text-dark">
					    	{{rental.get_address}}
					    </h6>
					  </div>
					</div>
				</div>

				<div class="pb-3">
					<div class="card" style="width: 16rem">
					  <div class="card-body my-3">   
					    <h6 class="card-subtitle my-2 text-dark text-center">Total profit for {{rental}}:</h6>
					    <h3 class="card-title my-1 text-center text-dark">{{this_total_profit|floatformat:2}}</h3>
					  </div>
					</div>
				</div>
				<div class="pb-3">
					<div class="card" style="width: 16rem">
					  <div class="card-body my-3">   
					    <h6 class="card-subtitle my-3 text-dark text-sm text-center">Number of transactions for {{rental}}:</h6>
					    <h3 class="card-title my-1 text-center text-dark">{{rental_units_count}}</h3>
					  </div>
					</div>
				</div>

			{% else %}	
				<div class="pb-4">
					<div class="card" style="width: 16rem">
					  <div class="card-body my-3">   
					    <h6 class="card-subtitle my-3 text-dark text-center">Total profit:</h6>
					    <h3 class="card-title my-1 text-center text-dark">{{total_profit|floatformat:2}}</h3>
					  </div>
					</div>
				</div>
				<div class="pb-4">
					<div class="card" style="width: 16rem">
					  <div class="card-body my-3">   
					    <h6 class="card-subtitle my-3 text-dark text-center">Total number of rental units:</h6>
					    <h3 class="card-title my-1 text-center text-dark">{{rental_units_count}}</h3>
					  </div>
					</div>
				</div>

				<div class="pb-4">
					<div class="card" style="width: 16rem">
					  <div class="card-body my-3">   
					    <h6 class="card-subtitle mt-1 mb-3 text-dark text-center">Total number of transactions:</h6>
					    <h3 class="card-title my-1 text-center">{{transactions_count}}</h3>
					  </div>
					</div>
				</div>
			{% endif%}
		</div>

		
		
	</div>
</div>

	

{% endblock content %}

calculator/templates/calculator/transaction_confirm_delete.html
{% extends "calculator/base.html" %}

{% block content %}
<form method="post">
	{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>
{% endblock content %}

calculator/templates/calculator/transactions.html
{% extends 'calculator/base.html' %}

{% load widget_tweaks %}

{% block content %}

{% for trans in transactions%}
	<!-- Modal -->
	<div class="modal fade" id="MyModal{{trans.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	  <div class="modal-dialog">
	    <div class="modal-content">
	      <div class="modal-header">
	        <h5 class="modal-title" id="exampleModalLabel">Comment</h5>
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
	          <span aria-hidden="true">&times;</span>
	        </button>
	      </div>
	      <div class="modal-body">
	      	<h6 class="pb-2">for:  {{trans}}</h6>
	      	<h6>comment:  <strong>{{trans.comments}}</strong></h6>
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
	      </div>
	    </div>
	  </div>
	</div>
{% endfor %}



<h2 class="text-center font-weight-bolder py-2"> All Transactions </h2>

<div class="row pb-4">
<a type="button" class="btn btn-outline-info btn-block" href="{% url 'rentalunit-create' %}">Add a Rental Unit</a>
</div>


<div class="py-2">
		<form method="get">
			<div class="row">
				<div class = "col col-5">
					<div class="input-group mb-1">
					  <div class="input-group-prepend">
					    <span class="input-group-text" id="basic-addon1">
					    	Select date from:
					    </span>
					  </div>
					  {% render_field myFilter.form.date_from class="form-control" placeholder="YYYY-MM-DD"%}
					</div>
				</div>

				<div class = "col col-5">
					<div class="input-group mb-1">
					  <div class="input-group-prepend">
					    <span class="input-group-text" id="basic-addon1">
					    	Select date to:
					    </span>
					  </div>
					  {% render_field myFilter.form.date_to class="form-control" placeholder="YYYY-MM-DD"%}
					</div>
				</div>

				<div class = "col col-1">
					<button class="btn btn-primary" type="submit">Search</button>
				</div>
			</div>

		</form>
</div>


<!-- table-->
	<table class="table table-hover">
	  <thead>
	    <tr>
	      <th scope="col" class= text>#</th>
	      <th scope="col" class= text>Rental Unit</th>
	      <th scope="col" class= text>Transaction type</th>
	      <th scope="col" class= text-center>Amount</th>
	      <th scope="col" class= text-center>Date</th>
	      <th scope="col" class= text-center>Comments</th>
	      <th scope="col" class= text>PDF</th>
	      <th scope="col" class= text>Remove</th>
	    </tr>
	  </thead>
	  
	  <tbody>
	  {% for trans in transactions%}
	  	<tr>

	  	</tr>
	  		<th scope="row">{{ forloop.counter}}</th>
	  		<td class="text">{{trans.rental_unit_id}}</th>

	    	{% if trans.transaction_type == "R"%}
	      		<td class="text-success">{{trans.get_transaction_type_display}}</td>
	      		<td class="text-success text-center">{{trans.amount}}</td>
	      	{% else %}
	      		<td class="text-danger">{{trans.get_transaction_type_display}}</td>
	      		<td class="text-danger text-center">{{trans.amount}}</td>
	      	{% endif %}

	      	<td class="text-center">{{trans.transaction_date}}</td>

			<!-- Comment button trigger modal -->
			{% if trans.comments != "-"%}
				<td class="text-center">
					<button type="button" class="btn btn-outline-dark" data-toggle="modal" data-target="#MyModal{{trans.id}}">View
					</button>
				</td>
			{% else %}
				<td class="text-center">-----</td>
			{% endif %}

	      	{% if trans.pdf_file %}
	      		<td><a href="{{trans.pdf_file.url}}" target="_blank">
	      			<svg class="bi bi-file-earmark-minus text-secondary text-center" width="2em" height="2em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  					<path d="M9 1H4a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h5v-1H4a1 1 0 0 1-1-1V3a1 1 0 0 1 1-1h5v2.5A1.5 1.5 0 0 0 10.5 6H13v2h1V6L9 1z"/>
  					<path fill-rule="evenodd" d="M11 11.5a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1h-4a.5.5 0 0 1-.5-.5z"/>
					</svg>
				</a></td>
	      	{% else %}
	      		<td class="text">-----</td>
	      	{% endif %}

	      	<td><a class="btn btn-secondary" href="{% url 'transaction-delete' trans.pk %}">delete</a></td>
	    </tr>	    
	    
	  {% endfor %}
	  </tbody>

	</table>
{% endblock content %}